apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
spec: {}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: game-2048
  name: game-2048
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-2048
    spec:
      containers:
        - image: public.ecr.aws/l6m2t8p7/docker-2048
          imagePullPolicy: Always
          name: game-2048
          ports:
            - containerPort: 80
